import type { Post } from "./types";

const base = Date.now();

function hoursFromNow(hours: number): string {
  return new Date(base + hours * 3600_000).toISOString();
}

interface Seed {
  id: string;
  type: string;
  title: string;
  description: string;
  skills: string[];
  authorName: string;
  authorMajor: string;
  authorGrade: string;
  createdAt: string;
  gradePreference?: string;
  hours: number;
  startHours?: number;
}

const seeds: Seed[] = [
  // 学业成长 · 竞赛搭子
  {
    id: "mock-1",
    type: "competition",
    title: "大创项目找一名会 UI 设计的队友",
    description:
      "我们正在做校园互助类小程序，已有产品和开发，想找会 Figma、能做移动端界面的同学一起申报大创。",
    skills: ["UI设计", "Figma", "移动端"],
    authorName: "小林",
    authorMajor: "计算机",
    authorGrade: "大三",
    createdAt: "10 分钟前",
    gradePreference: "大二/大三",
    hours: 72,
    startHours: -1,
  },
  {
    id: "mock-2",
    type: "competition",
    title: "数学建模比赛缺一名会 Python 的队友",
    description:
      "已有两人，一人建模、一人写论文，希望找熟悉 Python、能做数据分析和可视化的同学。",
    skills: ["Python", "数据分析", "数学建模"],
    authorName: "阿哲",
    authorMajor: "统计学",
    authorGrade: "大二",
    createdAt: "35 分钟前",
    gradePreference: "不限",
    hours: 48,
    startHours: -2,
  },
  {
    id: "mock-3",
    type: "competition",
    title: "挑战杯找一名会做数据可视化的队友",
    description:
      "项目方向是校园消费行为分析，已有数据和结论，需要会用 ECharts 或 Tableau 做展示的同学。",
    skills: ["数据可视化", "ECharts", "Tableau"],
    authorName: "小何",
    authorMajor: "经济学",
    authorGrade: "大三",
    createdAt: "今天",
    gradePreference: "不限",
    hours: 96,
    startHours: -3,
  },
  {
    id: "mock-4",
    type: "competition",
    title: "互联网+ 项目找文案和答辩帮手",
    description:
      "项目已进校赛，需要一个会写商业计划书、能帮忙打磨路演稿的队友，一起冲省赛。",
    skills: ["文案", "商业计划书", "路演"],
    authorName: "小盛",
    authorMajor: "工商管理",
    authorGrade: "大三",
    createdAt: "2 小时前",
    gradePreference: "不限",
    hours: 120,
    startHours: -4,
  },
  {
    id: "mock-5",
    type: "competition",
    title: "电子设计竞赛找一名硬件方向队友",
    description:
      "我们做的是智能小车方向，想找会画 PCB、能调试单片机的同学，实验室可以一起用。",
    skills: ["单片机", "PCB", "硬件"],
    authorName: "小韩",
    authorMajor: "电子信息",
    authorGrade: "大二",
    createdAt: "今天",
    gradePreference: "大二/大三",
    hours: 168,
    startHours: -5,
  },
  {
    id: "mock-6",
    type: "competition",
    title: "大创结题在即，找一名会做答辩 PPT 的同学",
    description:
      "内容已经整理好了，需要一位审美在线、会做 PPT 和图表排版的同学帮忙冲刺结题。",
    skills: ["PPT", "排版", "答辩"],
    authorName: "小姚",
    authorMajor: "生物工程",
    authorGrade: "大三",
    createdAt: "昨天",
    gradePreference: "不限",
    hours: 36,
    startHours: -12,
  },
  // 学业成长 · 备考搭子
  {
    id: "mock-7",
    type: "exam",
    title: "找图书馆考研搭子，互相监督打卡",
    description:
      "准备考研，一个人容易摆烂，想找每天一起在图书馆学习的搭子，互相打卡、互相监督。",
    skills: ["考研", "自习", "自律"],
    authorName: "小赵",
    authorMajor: "汉语言文学",
    authorGrade: "大三",
    createdAt: "今天",
    gradePreference: "不限",
    hours: 168,
    startHours: -4,
  },
  {
    id: "mock-8",
    type: "exam",
    title: "考公搭子，主攻行测和申论",
    description:
      "想找一两位一起备考公务员的同学，每周固定线上复盘一次，互相批改申论。",
    skills: ["考公", "行测", "申论"],
    authorName: "小冯",
    authorMajor: "法学",
    authorGrade: "大四",
    createdAt: "3 小时前",
    gradePreference: "大四/研究生",
    hours: 240,
    startHours: -6,
  },
  {
    id: "mock-9",
    type: "exam",
    title: "四六级冲刺搭子，每天互相听写单词",
    description:
      "距离考试还有一个月，想找人每天固定时间互测单词和听力，互相监督。",
    skills: ["四六级", "英语", "单词"],
    authorName: "小唐",
    authorMajor: "旅游管理",
    authorGrade: "大二",
    createdAt: "1 小时前",
    gradePreference: "不限",
    hours: 72,
    startHours: -1,
  },
  // 学业成长 · 课业求助 / 科研
  {
    id: "mock-10",
    type: "coursework",
    title: "高数期末求一位能讲题的学长学姐",
    description:
      "高数下册有几章没听懂，想找人约时间讲一讲重点，可以请喝奶茶或者付费。",
    skills: ["高数", "答疑", "期末"],
    authorName: "小季",
    authorMajor: "材料科学",
    authorGrade: "大一",
    createdAt: "4 小时前",
    gradePreference: "不限",
    hours: 24,
    startHours: -4,
  },
  {
    id: "mock-11",
    type: "coursework",
    title: "想互换《数据结构》和《操作系统》课件",
    description:
      "我这边有完整的课堂笔记和往年题，想换计科方向的课件和复习资料。",
    skills: ["课件", "笔记", "复习资料"],
    authorName: "小尹",
    authorMajor: "软件工程",
    authorGrade: "大二",
    createdAt: "昨天",
    gradePreference: "不限",
    hours: 120,
    startHours: -20,
  },
  {
    id: "mock-12",
    type: "coursework",
    title: "毕业论文求帮忙查重和降重",
    description:
      "初稿已经写完，重复率有点高，希望找有经验的同学帮忙看看怎么改，有偿。",
    skills: ["论文", "查重", "降重"],
    authorName: "小秦",
    authorMajor: "会计学",
    authorGrade: "大四",
    createdAt: "今天",
    gradePreference: "不限",
    hours: 48,
    startHours: -8,
  },
  {
    id: "mock-13",
    type: "research",
    title: "找文献共读搭子，方向是推荐系统",
    description:
      "每周一起读两篇论文并做笔记，互相讲给对方听，希望有一定英文阅读能力。",
    skills: ["文献", "论文", "推荐系统"],
    authorName: "小沈",
    authorMajor: "人工智能",
    authorGrade: "大三",
    createdAt: "2 小时前",
    gradePreference: "大三/研究生",
    hours: 168,
    startHours: -2,
  },
  {
    id: "mock-14",
    type: "research",
    title: "本科生想进课题组，找师兄师姐带一带",
    description:
      "对计算机视觉方向很感兴趣，想了解怎么找导师、怎么读第一篇论文，可以帮忙打杂。",
    skills: ["科研", "进组", "计算机视觉"],
    authorName: "小薛",
    authorMajor: "计算机",
    authorGrade: "大二",
    createdAt: "昨天",
    gradePreference: "不限",
    hours: 240,
    startHours: -30,
  },
  // 生活互助 · 校园跑腿
  {
    id: "mock-15",
    type: "errand",
    title: "有偿代取快递，菜鸟驿站到 3 号宿舍楼",
    description:
      "今天下午有课走不开，想找人帮忙代取一个快递送到 3 号宿舍楼下，可以付跑腿费。",
    skills: ["跑腿", "代取快递"],
    authorName: "小许",
    authorMajor: "机械工程",
    authorGrade: "大二",
    createdAt: "1 小时前",
    gradePreference: "不限",
    hours: 12,
    startHours: -1,
  },
  {
    id: "mock-16",
    type: "errand",
    title: "帮忙代打印一份 60 页的资料",
    description:
      "文件已经发给你，想找人帮我打印并装订，送到图书馆门口，费用当天结。",
    skills: ["代打印", "跑腿"],
    authorName: "小邓",
    authorMajor: "教育学",
    authorGrade: "大三",
    createdAt: "2 小时前",
    gradePreference: "不限",
    hours: 8,
    startHours: -2,
  },
  {
    id: "mock-17",
    type: "errand",
    title: "晚上帮忙带一杯奶茶到图书馆",
    description:
      "复习走不开，想找人顺路带一杯奶茶，钱先转给你，麻烦少冰。",
    skills: ["带饭", "跑腿", "奶茶"],
    authorName: "小曾",
    authorMajor: "新闻传播",
    authorGrade: "大二",
    createdAt: "今天",
    gradePreference: "不限",
    hours: 6,
    startHours: -1,
  },
  // 生活互助 · 闲置交换
  {
    id: "mock-18",
    type: "swap",
    title: "出二手《线性代数》和《概率论》教材",
    description:
      "课本九成新，没有笔记，两本打包便宜出，可以在图书馆或宿舍区自取。",
    skills: ["二手教材", "卖书"],
    authorName: "小彭",
    authorMajor: "数学",
    authorGrade: "大三",
    createdAt: "今天",
    gradePreference: "不限",
    hours: 120,
    startHours: -6,
  },
  {
    id: "mock-19",
    type: "swap",
    title: "闲置吉他转让，适合新手",
    description:
      "买来练了两个月，基本全新，想低价转给想学的同学，可以当面试琴。",
    skills: ["吉他", "闲置", "转让"],
    authorName: "小范",
    authorMajor: "土木工程",
    authorGrade: "大二",
    createdAt: "昨天",
    gradePreference: "不限",
    hours: 168,
    startHours: -24,
  },
  // 生活互助 · 拼车 / 室友 / 搬家 / 饭搭子
  {
    id: "mock-20",
    type: "carpool",
    title: "国庆拼车回家，找 2 位同学同行",
    description:
      "从学校回石家庄，计划 9 月 30 日下午出发，想找 2 位同学一起拼车分摊费用。",
    skills: ["拼车", "国庆", "石家庄"],
    authorName: "小孙",
    authorMajor: "土木工程",
    authorGrade: "大三",
    createdAt: "3 小时前",
    gradePreference: "不限",
    hours: 72,
    startHours: -3,
  },
  {
    id: "mock-21",
    type: "carpool",
    title: "周末去机场拼车，早上 6 点出发",
    description:
      "周六早班机，想找人一起拼车去机场，从学校南门出发，费用 AA。",
    skills: ["拼车", "机场", "周末"],
    authorName: "小贺",
    authorMajor: "英语",
    authorGrade: "大四",
    createdAt: "2 小时前",
    gradePreference: "不限",
    hours: 48,
    startHours: -2,
  },
  {
    id: "mock-22",
    type: "roommate",
    title: "校外合租找室友，两室一厅",
    description:
      "在学校附近看了一套两室一厅，想找一位作息规律的女生合租，可以先一起看房。",
    skills: ["合租", "找室友", "校外租房"],
    authorName: "小郑",
    authorMajor: "英语",
    authorGrade: "大四",
    createdAt: "今天",
    gradePreference: "不限",
    hours: 120,
    startHours: -5,
  },
  {
    id: "mock-23",
    type: "roommate",
    title: "宿舍床位转租，下学期可入住",
    description:
      "因为要出去实习，想转租一个四人间床位，价格可谈，需要的同学可以联系我。",
    skills: ["床位", "转租", "宿舍"],
    authorName: "小罗",
    authorMajor: "市场营销",
    authorGrade: "大三",
    createdAt: "昨天",
    gradePreference: "不限",
    hours: 240,
    startHours: -28,
  },
  {
    id: "mock-24",
    type: "moving",
    title: "毕业搬宿舍，找两位同学帮忙搬行李",
    description:
      "东西不多，主要是几个箱子和一床被子，从 6 号楼搬到校门口，时间可以商量。",
    skills: ["搬家", "搬行李"],
    authorName: "小石",
    authorMajor: "自动化",
    authorGrade: "大四",
    createdAt: "今天",
    gradePreference: "不限",
    hours: 36,
    startHours: -4,
  },
  {
    id: "mock-25",
    type: "meal",
    title: "找食堂饭搭子，中午一起吃饭",
    description:
      "一个人吃饭有点无聊，想找固定饭搭子，中午 12 点在一食堂碰头，聊聊天。",
    skills: ["饭搭子", "食堂", "干饭"],
    authorName: "小崔",
    authorMajor: "化学",
    authorGrade: "大二",
    createdAt: "1 小时前",
    gradePreference: "不限",
    hours: 72,
    startHours: -1,
  },
  // 兴趣搭子 · 游戏 / 运动 / 出游 / 摄影 / 阅读
  {
    id: "mock-26",
    type: "game",
    title: "找一起打王者的游戏搭子",
    description:
      "想找几个固定队友晚上一起开黑，段位不限，主要是图开心，不骂人就行。",
    skills: ["王者荣耀", "开黑", "游戏搭子"],
    authorName: "小吴",
    authorMajor: "软件工程",
    authorGrade: "大二",
    createdAt: "2 小时前",
    gradePreference: "不限",
    hours: 240,
    startHours: -2,
  },
  {
    id: "mock-27",
    type: "game",
    title: "原神萌新求带，想找人一起做副本",
    description:
      "刚玩不久，很多机制还不懂，想找一位有耐心的大佬带一带，平时也可以一起玩。",
    skills: ["原神", "副本", "游戏"],
    authorName: "小柏",
    authorMajor: "环境设计",
    authorGrade: "大一",
    createdAt: "今天",
    gradePreference: "不限",
    hours: 168,
    startHours: -6,
  },
  {
    id: "mock-28",
    type: "game",
    title: "周末桌游搭子，狼人杀 / 剧本杀都行",
    description:
      "想组一个固定桌游小队，周末在学校附近玩，人数不够时也可以线上连麦。",
    skills: ["桌游", "狼人杀", "剧本杀"],
    authorName: "小龚",
    authorMajor: "历史学",
    authorGrade: "大三",
    createdAt: "昨天",
    gradePreference: "不限",
    hours: 120,
    startHours: -18,
  },
  {
    id: "mock-29",
    type: "sports",
    title: "找羽毛球搭子，每周三晚上体育馆",
    description:
      "水平一般，想找固定球友一起打球，互相对练提高，球拍和球我可以多带一副。",
    skills: ["羽毛球", "运动"],
    authorName: "小冯",
    authorMajor: "视觉传达",
    authorGrade: "大三",
    createdAt: "昨天",
    gradePreference: "不限",
    hours: 168,
    startHours: -8,
  },
  {
    id: "mock-30",
    type: "sports",
    title: "夜跑搭子，操场每晚 9 点见",
    description:
      "想找人一起夜跑，互相监督不至于偷懒，配速 6 分左右，距离从 3 公里开始。",
    skills: ["跑步", "夜跑", "运动"],
    authorName: "小段",
    authorMajor: "体育教育",
    authorGrade: "大二",
    createdAt: "今天",
    gradePreference: "不限",
    hours: 240,
    startHours: -5,
  },
  {
    id: "mock-31",
    type: "sports",
    title: "健身房搭子，互相保护、一起打卡",
    description:
      "刚开始健身，想找一位有经验的同学带一带，主要练力量和增肌，一周去三次。",
    skills: ["健身", "力量训练"],
    authorName: "小柯",
    authorMajor: "机械工程",
    authorGrade: "大三",
    createdAt: "3 小时前",
    gradePreference: "不限",
    hours: 336,
    startHours: -3,
  },
  {
    id: "mock-32",
    type: "sports",
    title: "篮球半场组队，缺一名后卫",
    description:
      "每周六下午在体育馆打球，队伍还缺一名能控球的后卫，水平中等即可。",
    skills: ["篮球", "组队"],
    authorName: "小焦",
    authorMajor: "自动化",
    authorGrade: "大二",
    createdAt: "今天",
    gradePreference: "不限",
    hours: 96,
    startHours: -2,
  },
  {
    id: "mock-33",
    type: "outing",
    title: "找周末一起看展、爬山的朋友",
    description:
      "周末不想一直待在宿舍，想找喜欢看展、爬山、拍照的同学一起出去走走。",
    skills: ["看展", "爬山", "周末搭子"],
    authorName: "小冯",
    authorMajor: "视觉传达",
    authorGrade: "大三",
    createdAt: "昨天",
    gradePreference: "不限",
    hours: 50,
    startHours: -6,
  },
  {
    id: "mock-34",
    type: "outing",
    title: "周末去周边爬山，找同伴拼车",
    description:
      "计划周六去郊区爬山，当天来回，想找 3-4 位同学一起，可以拼车分摊费用。",
    skills: ["爬山", "拼车", "周末"],
    authorName: "小岳",
    authorMajor: "地理科学",
    authorGrade: "大三",
    createdAt: "2 小时前",
    gradePreference: "不限",
    hours: 72,
    startHours: -2,
  },
  {
    id: "mock-35",
    type: "outing",
    title: "电影搭子，想找人一起看新上映的片",
    description:
      "最近有几部电影想看，一个人去有点无聊，想找同样喜欢电影的同学一起。",
    skills: ["电影", "周末"],
    authorName: "小宁",
    authorMajor: "广播电视",
    authorGrade: "大二",
    createdAt: "今天",
    gradePreference: "不限",
    hours: 120,
    startHours: -7,
  },
  {
    id: "mock-36",
    type: "photography",
    title: "想找互拍搭子，拍一组校园写真",
    description:
      "不是专业摄影师，但会构图和后期，想找人互相拍一组校园照片，周末光线好的时候。",
    skills: ["摄影", "互拍", "写真"],
    authorName: "小尹",
    authorMajor: "广告学",
    authorGrade: "大三",
    createdAt: "昨天",
    gradePreference: "不限",
    hours: 168,
    startHours: -16,
  },
  {
    id: "mock-37",
    type: "reading",
    title: "读书会招人，这个月读《人类简史》",
    description:
      "想组一个 5-6 人的小读书会，每周线上聊一次，月底做一次线下分享。",
    skills: ["读书会", "共读", "分享"],
    authorName: "小蒋",
    authorMajor: "哲学",
    authorGrade: "大三",
    createdAt: "今天",
    gradePreference: "不限",
    hours: 336,
    startHours: -10,
  },
  // 求职技能
  {
    id: "mock-38",
    type: "job",
    title: "找求职搭子，互相改简历、模拟面试",
    description:
      "准备投互联网产品岗，想找一两位同学每周互相改简历、做一次模拟面试。",
    skills: ["简历", "面试", "产品岗"],
    authorName: "小陈",
    authorMajor: "金融学",
    authorGrade: "大三",
    createdAt: "2 小时前",
    gradePreference: "大三/大四",
    hours: 168,
    startHours: -2,
  },
  {
    id: "mock-39",
    type: "job",
    title: "秋招模拟面试搭子，目标运营岗",
    description:
      "想找人每周互相做一次行为面试，最好也投运营或市场方向，可以互相给反馈。",
    skills: ["模拟面试", "运营", "秋招"],
    authorName: "小凌",
    authorMajor: "新闻传播",
    authorGrade: "大四",
    createdAt: "4 小时前",
    gradePreference: "大四",
    hours: 120,
    startHours: -4,
  },
  {
    id: "mock-40",
    type: "job",
    title: "笔试刷题组队，主攻数据分析题",
    description:
      "想找 2-3 人一起刷笔试，每天晚上对答案、讲思路，主要练 SQL 和统计题。",
    skills: ["笔试", "SQL", "数据分析"],
    authorName: "小华",
    authorMajor: "统计",
    authorGrade: "大四",
    createdAt: "今天",
    gradePreference: "大四/研究生",
    hours: 96,
    startHours: -3,
  },
  {
    id: "mock-41",
    type: "skill",
    title: "想学 PS，可以教你 Python 入门交换",
    description:
      "我会一点 Python 和爬虫，想找人教我 PS 基础，互相教学，时间可以商量。",
    skills: ["PS", "Python", "技能交换"],
    authorName: "小闵",
    authorMajor: "信息管理",
    authorGrade: "大二",
    createdAt: "昨天",
    gradePreference: "不限",
    hours: 168,
    startHours: -14,
  },
  {
    id: "mock-42",
    type: "skill",
    title: "想找人帮忙剪一支 3 分钟社团招新视频",
    description:
      "素材已经拍好，大概 20 分钟原始视频，需要剪成 3 分钟左右的短片，可以付费。",
    skills: ["视频剪辑", "Premiere"],
    authorName: "小周",
    authorMajor: "新闻传播",
    authorGrade: "大四",
    createdAt: "1 小时前",
    gradePreference: "不限",
    hours: 24,
    startHours: -1,
  },
  {
    id: "mock-43",
    type: "skill",
    title: "C 语言期末救急，找一位能讲题的",
    description:
      "指针和结构体一直没搞明白，想找人约两小时讲清楚，可以请吃饭或付费。",
    skills: ["C语言", "编程", "答疑"],
    authorName: "小方",
    authorMajor: "通信工程",
    authorGrade: "大一",
    createdAt: "今天",
    gradePreference: "不限",
    hours: 48,
    startHours: -5,
  },
  {
    id: "mock-44",
    type: "parttime",
    title: "周末校园兼职组队，发传单",
    description:
      "看到一份周末兼职，想找几个人一起去，互相有个照应，有意向的可以一起报名。",
    skills: ["兼职", "社会实践"],
    authorName: "小常",
    authorMajor: "公共管理",
    authorGrade: "大二",
    createdAt: "昨天",
    gradePreference: "不限",
    hours: 72,
    startHours: -20,
  },
  {
    id: "mock-45",
    type: "parttime",
    title: "暑期社会实践组队，方向是乡村振兴",
    description:
      "想组一个 4 人小队做社会实践，需要会拍摄、会写报告、会做数据的同学。",
    skills: ["社会实践", "调研", "报告"],
    authorName: "小莫",
    authorMajor: "社会学",
    authorGrade: "大二",
    createdAt: "今天",
    gradePreference: "大一/大二",
    hours: 240,
    startHours: -9,
  },
  // 社交情感 / 紧急求助
  {
    id: "mock-46",
    type: "friend",
    title: "想认识新朋友，一起探索学校周边",
    description:
      "刚转专业过来，认识的人不多，想找几位同学周末一起吃饭、逛街、探索周边。",
    skills: ["交朋友", "探索"],
    authorName: "小苏",
    authorMajor: "建筑学",
    authorGrade: "大二",
    createdAt: "今天",
    gradePreference: "不限",
    hours: 168,
    startHours: -3,
  },
  {
    id: "mock-47",
    type: "cp",
    title: "找周末一起看展、喝咖啡的朋友",
    description:
      "想找兴趣相近的同学先做朋友，可以一起看展、喝咖啡、聊聊天，慢慢了解。",
    skills: ["周末搭子", "看展"],
    authorName: "小颜",
    authorMajor: "工业设计",
    authorGrade: "大三",
    createdAt: "昨天",
    gradePreference: "不限",
    hours: 120,
    startHours: -12,
  },
  {
    id: "mock-48",
    type: "emergency",
    title: "急借一个充电宝，图书馆三楼",
    description:
      "手机快没电了，还要等一个重要电话，有没有同学在图书馆三楼可以借一个充电宝。",
    skills: ["临时求助", "借东西"],
    authorName: "小任",
    authorMajor: "物理学",
    authorGrade: "大三",
    createdAt: "5 分钟前",
    gradePreference: "不限",
    hours: 6,
    startHours: -0.1,
  },
  {
    id: "mock-49",
    type: "lostfound",
    title: "寻找校园卡，昨天下午在操场丢失",
    description:
      "姓李，卡号后四位 8821，昨天下午在操场跑步时丢的，捡到的同学麻烦联系我。",
    skills: ["寻物", "校园卡"],
    authorName: "小李",
    authorMajor: "体育教育",
    authorGrade: "大二",
    createdAt: "1 小时前",
    gradePreference: "不限",
    hours: 48,
    startHours: -1,
  },
  {
    id: "mock-50",
    type: "competition",
    title: "数学建模还缺一名负责论文写作的队友",
    description:
      "建模和编程已经有人，想找一位文字表达好、能熬夜改论文的同学，一起冲国赛。",
    skills: ["论文写作", "数学建模", "LaTeX"],
    authorName: "小袁",
    authorMajor: "信息与计算科学",
    authorGrade: "大三",
    createdAt: "1 小时前",
    gradePreference: "大二/大三",
    hours: 96,
    startHours: -2,
  },
  {
    id: "mock-51",
    type: "exam",
    title: "雅思备考搭子，主攻口语和写作",
    description:
      "目标 7 分，想找人每周互相批改两篇作文、练两次口语，最好也在准备留学。",
    skills: ["雅思", "口语", "写作"],
    authorName: "小顾",
    authorMajor: "国际经贸",
    authorGrade: "大三",
    createdAt: "今天",
    gradePreference: "不限",
    hours: 240,
    startHours: -6,
  },
  {
    id: "mock-52",
    type: "coursework",
    title: "线性代数期末求辅导，可以付费",
    description:
      "矩阵和特征值部分一直没听懂，想找人约两次课讲一讲重点题型，价格好商量。",
    skills: ["线性代数", "辅导", "期末"],
    authorName: "小常",
    authorMajor: "电子商务",
    authorGrade: "大一",
    createdAt: "2 小时前",
    gradePreference: "不限",
    hours: 36,
    startHours: -2,
  },
  {
    id: "mock-53",
    type: "research",
    title: "毕业论文问卷还差 80 份，互相帮忙填",
    description:
      "我的问卷大概 3 分钟，填完可以互帮，也可以发小红包感谢，人多的话拉个群。",
    skills: ["问卷", "互助", "毕业论文"],
    authorName: "小尹",
    authorMajor: "心理学",
    authorGrade: "大四",
    createdAt: "今天",
    gradePreference: "不限",
    hours: 120,
    startHours: -5,
  },
  {
    id: "mock-54",
    type: "errand",
    title: "帮忙带一份晚饭到实验楼",
    description:
      "实验走不开，想找人从一食堂带一份饭到实验楼门口，可以付跑腿费。",
    skills: ["带饭", "跑腿"],
    authorName: "小庞",
    authorMajor: "化学工程",
    authorGrade: "大三",
    createdAt: "30 分钟前",
    gradePreference: "不限",
    hours: 6,
    startHours: -0.5,
  },
  {
    id: "mock-55",
    type: "swap",
    title: "毕业出一辆二手自行车，可小刀",
    description:
      "骑了两年，车况良好，刚换过刹车和车筐，毕业带不走，低价出给学弟学妹。",
    skills: ["自行车", "二手", "毕业"],
    authorName: "小孟",
    authorMajor: "电气工程",
    authorGrade: "大四",
    createdAt: "昨天",
    gradePreference: "不限",
    hours: 168,
    startHours: -22,
  },
  {
    id: "mock-56",
    type: "carpool",
    title: "寒假拼车去高铁站，早上 7 点出发",
    description:
      "放假回家，想找人拼车去高铁站，从学校东门出发，费用 AA，可以帮忙搬行李。",
    skills: ["拼车", "高铁站", "寒假"],
    authorName: "小尹",
    authorMajor: "汉语言文学",
    authorGrade: "大二",
    createdAt: "今天",
    gradePreference: "不限",
    hours: 72,
    startHours: -3,
  },
  {
    id: "mock-57",
    type: "roommate",
    title: "找研友合租，学校附近两室一厅",
    description:
      "准备二战考研，想找作息规律、安静的同学合租，房租大概 1500 左右，可以一起看房。",
    skills: ["合租", "考研", "找室友"],
    authorName: "小雷",
    authorMajor: "法学",
    authorGrade: "大四",
    createdAt: "2 小时前",
    gradePreference: "大四/研究生",
    hours: 240,
    startHours: -4,
  },
  {
    id: "mock-58",
    type: "game",
    title: "永劫无间找固定队友，晚上九点开黑",
    description:
      "技术一般但心态好，想找两三个固定队友一起玩，主打快乐游戏，不压力。",
    skills: ["永劫无间", "开黑", "游戏搭子"],
    authorName: "小殷",
    authorMajor: "数字媒体",
    authorGrade: "大二",
    createdAt: "今天",
    gradePreference: "不限",
    hours: 168,
    startHours: -7,
  },
  {
    id: "mock-59",
    type: "sports",
    title: "骑行搭子，周末沿江骑 30 公里",
    description:
      "想找人周末一起骑行，路线大概 30 公里，速度不快，安全第一，有装备更好。",
    skills: ["骑行", "运动", "周末"],
    authorName: "小温",
    authorMajor: "车辆工程",
    authorGrade: "大三",
    createdAt: "昨天",
    gradePreference: "不限",
    hours: 168,
    startHours: -26,
  },
  {
    id: "mock-60",
    type: "job",
    title: "产品岗求职搭子，一起做 mock 面试",
    description:
      "在准备互联网产品岗秋招，想找同方向的同学每周做一次 mock，互相复盘、互相改简历。",
    skills: ["产品岗", "模拟面试", "秋招"],
    authorName: "小苏",
    authorMajor: "市场营销",
    authorGrade: "大四",
    createdAt: "3 小时前",
    gradePreference: "大四/研究生",
    hours: 168,
    startHours: -3,
  },
  {
    id: "mock-61",
    type: "lostfound",
    title: "寻找丢失的蓝牙耳机，体育馆附近",
    description:
      "昨天在体育馆打完球发现耳机不见了，白色充电盒，上面有一个小猫贴纸，捡到请联系我。",
    skills: ["寻物", "耳机"],
    authorName: "小祝",
    authorMajor: "体育教育",
    authorGrade: "大一",
    createdAt: "1 小时前",
    gradePreference: "不限",
    hours: 48,
    startHours: -1,
  },
];

export const mockPosts: Post[] = seeds.map((seed) => ({
  id: seed.id,
  type: seed.type,
  title: seed.title,
  description: seed.description,
  skills: seed.skills,
  gradePreference: seed.gradePreference,
  authorName: seed.authorName,
  authorMajor: seed.authorMajor,
  authorGrade: seed.authorGrade,
  createdAt: seed.createdAt,
  status: "open" as const,
  displayStartAt: hoursFromNow(seed.startHours ?? -2),
  displayEndAt: hoursFromNow(seed.hours),
  durationMinutes: Math.round(seed.hours * 60),
}));
